import logging
import os
import re
import shutil
import traceback
import git
import json
import tiktoken
from json import JSONDecodeError
import ast
import textwrap
import requests
import pdfplumber
import tempfile
from datetime import datetime

from langchain_openai import ChatOpenAI, OpenAIEmbeddings, AzureChatOpenAI, AzureOpenAIEmbeddings
from langgraph.graph import StateGraph, END
from typing import List, Optional, Union, Tuple
from pydantic import BaseModel, Field, ValidationError
from typing import List, Dict, TypedDict, Optional, Any
from langchain_core.documents import Document
from langchain_community.document_loaders import GitLoader, RecursiveUrlLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
import json


# Configure root logger
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)
logging.getLogger("pdfminer.pdfpage").setLevel(logging.ERROR)


class ModelCard(BaseModel):
    """
    Pydantic model defining standardized metadata fields for a scientific software,
    model, dataset, or tool. Each field includes a default value and description
    to support automated or manual generation of model cards.
    """
    capability_name: str = Field(default="N/A", description="The primary name of the software, model, dataset, or tool.")
    brief_description: str = Field(default="N/A", description="A brief, one or two-sentence description of the software's main purpose and function.  What are the typical uses?  Who is currently using it?")
    systems_covered: str = Field(default="N/A", description="The real-world systems the model represents (e.g., energy systems, water resources, climate, ecosystems, land use, socioeconomics, machine learning models). List the main ones.")
    contact_name: str = Field(default="N/A", description="The name of the primary contact person for the software, if specified.")
    contact_email: str = Field(default="N/A", description="The email address of the primary contact person.")
    key_contributors: Union[List[str], str] = Field(default="N/A", description="Names or GitHub handles of other significant contributors mentioned.")
    doi: str = Field(default="N/A", description="The current Digital Object Identifier (DOI) for citing the software, if available (check CITATION.cff or README).")
    computational_requirements: Union[List[str], str] = Field(default="N/A", description="Hardware needed to run the software (e.g., Standard laptop, High-performance computing (HPC) cluster, GPU required).")
    sponsoring_projects: Union[List[str], str] = Field(default="N/A", description="Projects or funding agencies that sponsored the development, if mentioned.")
    figure: str = Field(default="N/A", description="Reference or URL to a key figure illustrating the software's structure or results, if described or linked in the text.")
    figure_caption: str = Field(default="N/A", description="The caption associated with the key figure, if available in the text.")
    spatial_resolution: Union[List[str], str] = Field(default="N/A", description="The spatial resolutions (range of tested grid spacing or distance between resolved features) at which the model can operate.  For example:  1 km, 5 arcmin, 0.5 degrees, Unstructured grid, Structured grid, Variable resolution, N/A if not applicable).  Return all that apply.")
    geographic_scope: Union[List[str], str] = Field(default="N/A", description="The geographic area the model covers or is applied to (e.g., Global, CONUS, specific region, point location). Mention both potential and current applications if specified.")
    temporal_resolution: Union[List[str], str] = Field(default="N/A", description="The time step or frequency of the model's calculations.  Either: seconds, minutes, hourly, daily, monthly, annual, 5-year, or decadal).  Return all that apply.")
    temporal_range: Union[List[str], str] = Field(default="N/A", description="The time period the model simulates.  Either: historical, future, specific period.  Return all that apply.")
    input_variables: Union[List[str], str] = Field(default="N/A", description="Key input data or variables required by the software.  List them.  Examples:  daily precipitation; power plant heat rate; locational marginal prices; gridded fractional land cover.")
    output_variables: Union[List[str], str] = Field(default="N/A", description="Key output data or results generated by the software. List them. Examples:  instantaneous cyclone energy; fractional land cover; monthly runoff; atmospheric radiation; daily precipitation.")
    interdependencies: Union[List[str], str] = Field(default="N/A", description="Other models, software libraries, or specific datasets the software relies on or commonly interacts with. For example, E3SM, GCAM, specific weather data).")
    key_publications: Union[List[str], str] = Field(default="N/A", description="List of key publications as found in the documentation or as provided as PDF files by the user.")
    category: Union[List[str], str] = Field(default="N/A", description="Select from:  Atmosphere, Physical Hydrology, Water Management, Wildfire, Energy, Multisectoral, Land Use Land Cover, Socioeconomics.  Return all that apply.")
    license: str = Field(default="N/A", description="The name of the license associated with the software, model, dataset, or tool.")
    current_version: str = Field(default="N/A", description="The current version of the software, model, dataset, or tool.")


class GraphState(TypedDict):
    """
    Represents the state of the graph as it progresses through document
    processing and model card generation.

    Attributes:
        input_urls (Dict[str, str]): A dictionary of input source URLs, keyed by source name.
        github_docs (Optional[List[Document]]): Documents retrieved from a GitHub repository.
        docs_docs (Optional[List[Document]]): Documents retrieved from a Google Docs source.
        extracted_info (Dict): Information extracted from the documents.
        model_card (Optional[Dict]): A dictionary representing the generated model card.
        error_messages (List[str]): A list of error messages encountered during processing.
        validation_issues (Dict): Validation issues detected during processing.
    """
    github_url: str
    github_branch: str
    github_content: Optional[List[Document]]
    docs_docs: Optional[List[Document]]
    publication_docs: Optional[List[Document]]
    extracted_info: Dict
    model_card: Optional[Dict]
    error_messages: List[str]
    validation_issues: Dict
    release_info: Dict
    github_release_errors: List[str]
    contributors_info: Dict
    github_contributor_errors: List[str]
    github_extracted_info: Dict
    github_repository_errors: List[str]
    handled_errors: List[str]
    llm_client: Any
    website_url: Optional[str]
    website_content: Optional[List[Document]]
    website_errors: List[str]
    website_extracted_info: Dict
    publication_directory: str
    publication_content: Optional[List[Document]]
    publication_extracted_info: Dict
    publication_errors: List[str]
    raw_extracted_info: Dict


def fetch_github_release(state: GraphState) -> Dict:
    """
    Fetch the latest GitHub release tag and store it as current_version.
    """
    logging.info("--- Node: fetch_github_release ---")

    extracted = state.get('extracted_info', {}) or {}
    errors = state.get('error_messages', []) or []
    git_url = state.get('github_url')

    if not git_url:
        errors.append("No GitHub URL provided for latest-release lookup.")
        return {"extracted_info": extracted, "error_messages": errors}

    try:
        # turn "https://github.com/owner/repo" into "owner/repo"
        owner_repo = git_url.rstrip("/").split("github.com/")[1]
        api_url = f"https://api.github.com/repos/{owner_repo}/releases/latest"

        resp = requests.get(api_url, timeout=10)
        # Handle forbidden access by setting N/A
        if resp.status_code == 403:
            logging.warning("GitHub release lookup forbidden (403); setting current_version to 'N/A'")
            extracted["current_version"] = "N/A"
            return {"release_info": extracted, "github_release_errors": errors}
        resp.raise_for_status()
        data = resp.json()

        tag = data.get("tag_name")
        if tag:
            previous = extracted.get("current_version")
            # Override any existing non-default version
            if previous and previous != tag and previous != "N/A":
                logging.info(f"Overriding existing current_version '{previous}' with latest release '{tag}'")
            extracted["current_version"] = tag
            logging.info(f"Retrieved latest release tag: {tag}")
        else:
            logging.warning("No tag_name field in GitHub response.")
            errors.append("GitHub release JSON missing tag_name.")
    except Exception as e:
        logging.warning(f"Failed to retrieve latest release: {e}")
        errors.append(f"Latest-release lookup error: {e}")

    return {"release_info": extracted, "github_release_errors": errors}


def fetch_github_contributors(state: GraphState) -> Dict:
    """
    Fetch the list of GitHub repository contributors and store their logins as key_contributors.
    """
    logging.info("--- Node: fetch_github_contributors ---")
    extracted = state.get('extracted_info', {}) or {}
    errors = state.get('error_messages', []) or []
    git_url = state.get('github_url')

    if not git_url:
        errors.append("No GitHub URL provided for contributors lookup.")
        return {"extracted_info": extracted, "error_messages": errors}

    try:
        # Extract "owner/repo" from the URL
        owner_repo = git_url.rstrip("/").split("github.com/")[1]
        api_url = f"https://api.github.com/repos/{owner_repo}/contributors"

        resp = requests.get(api_url, timeout=10)
        # Handle forbidden access by setting current_version to 'N/A'
        if resp.status_code == 403:
            logging.warning("GitHub contributors lookup forbidden (403); setting current_version to 'N/A'")
            extracted["current_version"] = "N/A"
            return {"contributors_info": extracted, "github_contributor_errors": errors}
        resp.raise_for_status()
        data = resp.json()

        # Extract login names along with actual names where available
        contributors = []
        for entry in data:
            login = entry.get("login")
            if not login:
                continue
            # Default to login if no real name found
            display_name = login
            try:
                user_api_url = entry.get("url")
                user_resp = requests.get(user_api_url, timeout=10)
                user_resp.raise_for_status()
                user_data = user_resp.json()
                name = user_data.get("name")
                if name:
                    display_name = name
            except Exception as e:
                logging.warning(f"Could not fetch user details for {login}: {e}")
            # Format as "Name (@login)" if name differs, otherwise just login
            if display_name and display_name.lower() != login.lower():
                contributors.append(f"{display_name} (@{login})")
            else:
                contributors.append(login)

        if contributors:
            previous = extracted.get("key_contributors")
            if previous and previous != "N/A":
                logging.info(f"Overriding existing key_contributors '{previous}' with fetched contributors list")
            extracted["key_contributors"] = contributors
            logging.info(f"Retrieved {len(contributors)} contributors")
        else:
            logging.warning("No contributors found in GitHub response.")
            errors.append("GitHub contributors JSON empty or missing logins.")
    except Exception as e:
        logging.warning(f"Failed to retrieve GitHub contributors: {e}")
        errors.append(f"Contributors lookup error: {e}")

    return {"contributors_info": extracted, "github_contributor_errors": errors}


def fetch_github_repository(
        state: GraphState,
        repository_clone_directory: str = "./data/temp_repo_clone",
        chunk_size: int = 1000,
        chunk_overlap: int = 150,
        file_extensions: List[str] = None,
):
    """
    Fetch and process documents from a GitHub repository.

    This function attempts to clone or fetch updates from a specified GitHub
    repository, then loads and splits documents from it using the
    RecursiveCharacterTextSplitter.

    Args:
        state (GraphState): The current graph state containing input URLs and error messages.
        repository_clone_directory (str): Directory path to clone or fetch the repository into.
        chunk_size (int): The maximum number of characters per document chunk.
        chunk_overlap (int): The number of overlapping characters between chunks.

    Returns:
        dict: A dictionary with the processed GitHub documents under "github_docs"
              and any encountered error messages under "error_messages".
    """
    logging.info("--- Node: fetch_github_repository ---")

    # Determine branch to use (default 'main', override via input_urls['github_branch'])
    branch = state.get('github_branch', 'main')

    github_url = state.get("github_url")
    errors = state.get('error_messages', []) or [] # Ensure errors list exists
    docs = None
    raw_docs = None
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)

    if not github_url:
        errors.append("Missing GitHub URL.")
        return {"github_content": None, "error_messages": errors}

    try:
        if os.path.exists(repository_clone_directory):
            try:
                logging.info(f"Repository directory exists at {repository_clone_directory}. Attempting git fetch...")

                repo = git.Repo(repository_clone_directory)

                if not repo.remotes:
                     raise git.InvalidGitRepositoryError(f"{repository_clone_directory} exists but has no remotes.")
                
                logging.info("Fetching updates from all remotes (--all --prune)...")
                repo.git.fetch('--all', '--prune')

                logging.info("Git fetch complete.")
                loader = GitLoader(repo_path=repository_clone_directory, branch=branch)

                raw_docs = loader.load()

            except git.InvalidGitRepositoryError as e:
                 logging.error(f"Existing directory {repository_clone_directory} is not a valid Git repository: {e}. Re-cloning...")
                 errors.append(f"InvalidGitRepositoryError for existing dir: {str(e)}")
                 shutil.rmtree(repository_clone_directory)
                 raw_docs = None

            except git.GitCommandError as e:
                logging.error(f"Git fetch error: {e}")
                errors.append(f"Git fetch failed: {str(e)}. Check permissions/repo state.")
                logging.info("Attempting to load documents from current state despite fetch error...")

                try:
                    loader = GitLoader(repo_path=repository_clone_directory, branch=branch)
                    raw_docs = loader.load()

                except Exception as load_e:
                    logging.error(f"Failed to load docs after fetch error: {load_e}")
                    errors.append(f"Failed to load docs after GitCommandError: {str(load_e)}")
                    raw_docs = None

            except Exception as e:
                logging.error(f"Accessing existing repo failed: {e}. Attempting re-clone...")
                errors.append(f"Error accessing existing repo: {str(e)}")

                try:
                    shutil.rmtree(repository_clone_directory)

                except OSError as rm_e:
                    logging.error(f"Failed to remove problematic directory: {rm_e}")
                    errors.append(f"Failed to remove problematic directory: {str(rm_e)}")

                raw_docs = None

        # If the directory didn't exist OR we decided to re-clone
        if not os.path.exists(repository_clone_directory) or raw_docs is None and github_url:
             try:
                logging.info(f"Cloning repository {github_url} to {repository_clone_directory}...")
                loader = GitLoader(clone_url=github_url, repo_path=repository_clone_directory, branch=branch)
                raw_docs = loader.load()
                logging.info("Clone complete.")
                
             except Exception as e:
                 logging.error(f"Cloning GitHub repo failed: {e}")
                 errors.append(f"GitHub clone failed: {str(e)}")
                 raw_docs = None

    except Exception as e:

        tb_str = traceback.format_exc()
        logging.critical(f"CRITICAL ERROR in fetch_github_repository: {e}\n{tb_str}")
        errors.append(f"Critical fetch_github_repository error: {str(e)}")
        docs = None

    # Process raw_docs through filter node
    docs, errors = filter_by_file_type(raw_docs, file_extensions, text_splitter, errors)    
    
    # reduce the file content by removing any latex or html tags
    if docs:
        cleaned_docs = []
        for doc in docs:
            cleaned_text = clean_content(doc.page_content)
            cleaned_docs.append(Document(page_content=cleaned_text, metadata=doc.metadata))
        docs = cleaned_docs

    # Log token count
    try:
        encoding = tiktoken.get_encoding("cl100k_base")
        num_tokens = len(encoding.encode("\n\n".join(doc.page_content for doc in docs)))
        logging.info(f"--- Node fetch_github_repository -- GitHub content requires {num_tokens} tokens")
    except Exception as e:
        logging.warning(f"Failed to count tokens for docs_text: {e}")


    return {"github_content": docs, "error_messages": errors}


# New node: fetch_website
def fetch_website(
        state: GraphState,
        timeout: int = 30,
        chunk_size: int = 1000,
        chunk_overlap: int = 150,
        max_depth: int = 3,
    ) -> Dict:
    """
    Fetch and process documents from a generic website.
    """
    logging.info("--- Node: fetch_website ---")

    errors: List[str] = []
    url = state.get("website_url")

    if not url:
        errors.append("No website URL provided.")
        return {"website_content": None, "website_errors": errors}
    
    try:
        # Load and split website content into Document chunks
        logging.info(f"Fetching website content from {url}")

        loader = RecursiveUrlLoader(
            url=url,
            max_depth=max_depth,
            prevent_outside=True,
            use_async=False,
            timeout=timeout,
        )
        
        raw_docs = loader.load()
        splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=150)
        docs = splitter.split_documents(raw_docs)
        logging.info(f"Processed {len(docs)} docs from website.")

    except Exception as e:
        logging.error(f"Failed to fetch or process website content: {e}")
        errors.append(f"Website fetch error: {e}")
        docs = None

    # reduce the file content by removing any latex or html tags
    if docs:
        cleaned_docs = []
        for doc in docs:
            cleaned_text = clean_content(doc.page_content)
            cleaned_docs.append(Document(page_content=cleaned_text, metadata=doc.metadata))
        docs = cleaned_docs

    # Log token count
    try:
        encoding = tiktoken.get_encoding("cl100k_base")
        num_tokens = len(encoding.encode("\n\n".join(doc.page_content for doc in docs)))
        logging.info(f"--- Node fetch_website -- Website content requires {num_tokens} tokens")
    except Exception as e:
        logging.warning(f"Failed to count tokens for docs_text: {e}")

    return {"website_content": docs, "website_errors": errors}


def fetch_publications_pdfs(state: GraphState) -> Dict:
    """
    Load local PDF files from a user-specified directory and extract their text for refinement.
    """
    logging.info("--- Node: fetch_publications_pdfs ---")

    errors = state.get('publication_errors', []) or []
    pdf_docs = []

    # Expect 'pdf_dir' in input_urls to specify where to load PDFs from
    pdf_dir = state.get("publication_directory")

    if not pdf_dir:
        errors.append("Missing PDF directory for publications ('pdf_dir' not provided).")
        return {"publication_content": [], "publication_errors": errors}
    
    if not os.path.isdir(pdf_dir):
        errors.append(f"PDF directory does not exist: {pdf_dir}")
        return {"publication_content": [], "publication_errors": errors}
    
    # Process each PDF file in the directory
    for fname in os.listdir(pdf_dir):
        if fname.lower().endswith('.pdf'):
            path = os.path.join(pdf_dir, fname)

            try:
                with pdfplumber.open(path) as pdf:
                    text = ""
                    for page in pdf.pages:
                        text += page.extract_text() or ""
                        text += "\n\n"

                collected_content = Document(page_content=text, metadata={'source': path})   
                pdf_docs.append(collected_content)

            except Exception as e:
                logging.error(f"Error processing PDF {path}: {e}")
                errors.append(str(e))

    return {"publication_content": pdf_docs, "publication_errors": errors}





# New node: extract_github_info
def extract_github_info(state: GraphState) -> Dict:
    """
    Extract information for the ModelCard from GitHub content using an LLM.
    """
    logging.info("--- Node: extract_github_info ---")

    docs = state.get("github_content") or []
    extracted = state.get("github_extracted_info", {}) or {}
    errors = state.get("github_repository_errors", []) or []

    extracted: Dict = {}

    # Prepare document text
    docs_text = "\n\n".join(doc.page_content for doc in docs)

    # Dynamically build list of field descriptions from the Pydantic ModelCard
    field_descriptions = "\n".join(
        f"- {name}: {field.description}"
        for name, field in ModelCard.model_fields.items()
    )
    
    prompt_template = f"""
You are an assistant that extracts metadata for a model card. The model card fields have the following names and descriptions:
{field_descriptions}

Given the following repository documents, extract these fields and output as a JSON object with the exact field names:

Repository documents content:
{{docs_text}}

JSON Output:
"""
    prompt = ChatPromptTemplate.from_template(prompt_template)
    chain = prompt | llm | StrOutputParser()

    try:
        result_str = chain.invoke({"docs_text": docs_text})

        # Handle empty or whitespace-only output
        if not result_str or not result_str.strip():
            logging.warning("Empty output from LLM during information extraction")
            errors.append("Empty LLM output for information extraction")
            extracted = {}
            return {"github_extracted_info": extracted, "github_repository_errors": errors}
        
        try:
            # Remove Markdown code fences if present
            cleaned = re.sub(r"```(?:json)?\s*", "", result_str)
            cleaned = re.sub(r"```", "", cleaned).strip()
            extracted = json.loads(cleaned)

        except JSONDecodeError as jde:
            logging.error(f"JSON parsing error during information extraction: {jde}")
            errors.append(f"JSON parsing error: {jde}. Raw output: {cleaned!r}")
            # Attempt to extract JSON substring
            match = re.search(r'(\{.*\})', cleaned, re.DOTALL)
            if match:
                try:
                    extracted = json.loads(match.group(1))
                except JSONDecodeError as jde2:
                    logging.error(f"Secondary JSON parsing error: {jde2}")
                    errors.append(f"Secondary JSON parsing error: {jde2}. Substring: {match.group(1)!r}")
                    extracted = {}
            else:
                extracted = {}

    except Exception as e:
        logging.error(f"Error during information extraction: {e}")
        errors.append(str(e))

    return {"github_extracted_info": extracted, "github_repository_errors": errors}

# New node: extract_website_info
def extract_website_info(state: GraphState) -> Dict:
    """
    Extract information for the ModelCard from website content using an LLM.
    """
    logging.info("--- Node: extract_website_info ---")
    
    docs = state.get("website_content") or []
    extracted = state.get("website_extracted_info", {}) or {}
    errors = state.get("website_errors", []) or []
    extracted: Dict = {}

    # Prepare document text
    docs_text = "\n\n".join(doc.page_content for doc in docs)

    # Dynamically build list of field descriptions from the Pydantic ModelCard
    field_descriptions = "\n".join(
        f"- {name}: {field.description}"
        for name, field in ModelCard.model_fields.items()
    )

    prompt_template = f"""
You are an assistant that extracts metadata for a model card. The model card fields have the following names and descriptions:
{field_descriptions}

Given the following website documents, extract these fields and output as a JSON object with the exact field names:

Website documents content:
{{docs_text}}

JSON Output:
"""
    prompt = ChatPromptTemplate.from_template(prompt_template)
    chain = prompt | llm | StrOutputParser()

    try:
        result_str = chain.invoke({"docs_text": docs_text})

        # Handle empty or whitespace-only output
        if not result_str or not result_str.strip():
            logging.warning("Empty output from LLM during website information extraction")
            errors.append("Empty LLM output for website information extraction")
            extracted = {}
            return {"website_extracted_info": extracted, "website_errors": errors}
        
        try:
            # Remove Markdown code fences if present
            cleaned = re.sub(r"```(?:json)?\s*", "", result_str)
            cleaned = re.sub(r"```", "", cleaned).strip()
            extracted = json.loads(cleaned)

        except JSONDecodeError as jde:
            logging.error(f"JSON parsing error during website information extraction: {jde}")
            errors.append(f"JSON parsing error: {jde}. Raw output: {cleaned!r}")
            # Attempt to extract JSON substring
            match = re.search(r'(\{.*\})', cleaned, re.DOTALL)
            if match:
                try:
                    extracted = json.loads(match.group(1))
                except JSONDecodeError as jde2:
                    logging.error(f"Secondary JSON parsing error: {jde2}")
                    errors.append(f"Secondary JSON parsing error: {jde2}. Substring: {match.group(1)!r}")
                    extracted = {}
            else:
                extracted = {}

    except Exception as e:
        logging.error(f"Error during website information extraction: {e}")
        errors.append(str(e))

    return {"website_extracted_info": extracted, "website_errors": errors}


# New node: extract_publication_info
def extract_publication_info(state: GraphState) -> Dict:
    """
    Extract information for the ModelCard from local publication PDFs using an LLM.
    """
    logging.info("--- Node: extract_publication_info ---")
    docs = state.get("publication_content") or []
    extracted: Dict = {}
    errors = state.get("publication_errors", []) or []

    # Prepare document text
    docs_text = "\n\n".join(doc.page_content for doc in docs)

    # Build field descriptions from ModelCard
    field_descriptions = "\n".join(
        f"- {name}: {field.description}"
        for name, field in ModelCard.model_fields.items()
    )

    prompt_template = f"""
You are an assistant that extracts metadata for a model card. The model card fields have the following names and descriptions:
{field_descriptions}

Given the following publication document texts, extract these fields and output as a JSON object with the exact field names:

Publication documents content:
{{docs_text}}

JSON Output:
"""
    prompt = ChatPromptTemplate.from_template(prompt_template)
    chain = prompt | llm | StrOutputParser()

    try:
        result_str = chain.invoke({"docs_text": docs_text})

        if not result_str or not result_str.strip():
            logging.warning("Empty LLM output for publication information extraction")
            errors.append("Empty LLM output for publication information extraction")
            return {"publication_extracted_info": {}, "publication_errors": errors}

        # Clean and parse
        cleaned = re.sub(r"```(?:json)?\s*", "", result_str)
        cleaned = re.sub(r"```", "", cleaned).strip()
        try:
            extracted = json.loads(cleaned)
        except JSONDecodeError as jde:
            logging.error(f"JSON parsing error for publications: {jde}")
            errors.append(f"JSON parsing error: {jde}")
            extracted = {}
    except Exception as e:
        logging.error(f"Error during publication information extraction: {e}")
        errors.append(str(e))

    return {"publication_extracted_info": extracted, "publication_errors": errors}


def clean_content(text: str) -> str:
    """
    Remove HTML tags and LaTeX expressions from text.
    """
    # Remove HTML tags
    cleaned = re.sub(r'<[^>]+>', '', text)
    # Remove inline LaTeX math ($...$)
    cleaned = re.sub(r'\$.*?\$', '', cleaned)
    # Remove LaTeX commands like \command{...}
    cleaned = re.sub(r'\\[a-zA-Z]+\{.*?\}', '', cleaned)

    return cleaned


# Helper function: filter_by_file_type
def filter_by_file_type(
    raw_docs: Optional[List[Document]],
    file_extensions: List[str],
    text_splitter: RecursiveCharacterTextSplitter,
    errors: List[str],
) -> Tuple[Optional[List[Document]], List[str]]:
    """
    Convert PDFs to text, filter by allowed extensions (and LICENSE files),
    then split into document chunks.
    """

    if not raw_docs:
        logging.warning("No documents to filter or process.")
        return None, errors

    if file_extensions is None:
        file_extensions = [
            '.txt', '.md', '.rst', '.png', '.jpg', '.svg',
            '.cff', '.json', '.yaml', '.sh', '.cfg', '.config',
            '.cmake', '.xml', 'makefile', '.rd', '.rmd', '.toml',
            '.poetry', '.tex', '.bib', ''
        ]

    # 1) Convert any PDFs to plain-text Documents
    converted = []
    for doc in raw_docs:
        source = doc.metadata.get('source', '')
        if source.lower().endswith('.pdf'):
            try:
                with pdfplumber.open(source) as pdf:
                    text = ""
                    for page in pdf.pages:
                        text += page.extract_text() or ""
                        text += "\n\n"
                converted.append(Document(page_content=text, metadata=doc.metadata))
            except Exception as e:
                logging.error(f"Error converting PDF {source}: {e}")
                errors.append(f"PDF conversion error for {source}: {e}")
        else:
            converted.append(doc)

    # 2) Filter by extension or LICENSE filenames
    filtered = []
    for doc in converted:
        source = doc.metadata.get('source', '')
        _, ext = os.path.splitext(source)
        name = os.path.basename(source).lower()
        if ext.casefold() in file_extensions or name in ("license", "license.md", "license.txt"):
            filtered.append(doc)

    # 3) Split into final document chunks
    docs = text_splitter.split_documents(filtered)

    logging.info(f"Processed {len(docs)} docs from GitHub.")
    return docs, errors



def handle_error(state: GraphState) -> Dict:
    """
    Handle errors encountered in the workflow by logging them and consolidating validation issues.

    Args:
        state (GraphState): The current graph state containing 'error_messages' and 'validation_issues'.

    Returns:
        dict: A dictionary with 'handled_errors' updated to include any validation issues.
    """
    logging.info("--- Node: handle_error ---")
    errors = state.get('error_messages', []) or []
    issues = state.get('validation_issues', []) or []

    # Merge validation issues into error messages
    for issue in issues:
        errors.append(f"Validation issue: {issue}")

    logging.error(f"Workflow encountered errors: {errors}")

    return {"handled_errors": errors}


def build_model_card(state: GraphState) -> Dict:
    """
    Build the final model_card from extracted_info.
    """
    logging.info("--- Node: build_model_card ---")
    extracted = state.get('extracted_info', {}) or {}
    # Normalize values for model card compatibility
    normalized = {}
    for key, value in extracted.items():
        # Replace None with "N/A"
        if value is None:
            normalized[key] = "N/A"
        # Join lists for string-only fields
        elif key == 'systems_covered' and isinstance(value, list):
            normalized[key] = ", ".join(value)
        else:
            normalized[key] = value

    # Ensure figure path has a valid image extension
    fig = normalized.get("figure")
    if isinstance(fig, str):
        if not re.search(r'\.(png|jpe?g)$', fig, re.IGNORECASE):
            logging.info(f"Invalid figure extension for '{fig}', setting to N/A")
            normalized["figure"] = "N/A"

    return {"model_card": normalized}


def merge_info(state: GraphState) -> Dict:
    """
    Merge release_info and contributors_info into extracted_info and combine errors.
    """
    logging.info("--- Node: merge_info ---")

    # Card information extracted from various resources
    github_version = state.get("release_info", {}) or {}
    github_contributors = state.get("contributors_info", {}) or {}
    github_information = state.get("github_extracted_info", {}) or {}
    website_information = state.get("website_extracted_info", {}) or {}

    # Errors logged for each node
    github_repository_errors = state.get("github_repository_errors", []) or []
    github_release_errors = state.get("github_release_errors", []) or []
    github_contributor_errors = state.get("github_contributor_errors", []) or []
    website_errors = state.get("website_errors", []) or []

    # Combined error logs
    merged_errors = github_release_errors + github_contributor_errors + github_repository_errors + website_errors

    merged: Dict = {}

    # 1 & 2: Apply GitHub version and contributors with priority
    if github_version.get("current_version") and github_version.get("current_version") != "N/A":
        merged["current_version"] = github_version["current_version"]

    if github_contributors.get("key_contributors") and github_contributors.get("key_contributors") != "N/A":
        merged["key_contributors"] = github_contributors["key_contributors"]

    # 3: Merge GitHub-derived information, respecting version/contributors priority
    for key, value in github_information.items():
        if key == "current_version" and merged.get("current_version") is not None:
            continue
        if key == "key_contributors" and merged.get("key_contributors") is not None:
            continue
        merged[key] = value

    # 4: Merge website information by appending new values
    for key, value in website_information.items():
        
        if key in ("current_version", "key_contributors"):
            continue
        
        existing = merged.get(key)
        if existing is None:
            merged[key] = value
        else:
            # Combine list and list
            if isinstance(existing, list) and isinstance(value, list):
                merged[key] = list(dict.fromkeys(existing + value))
            # Existing list, new string – keep list semantics
            elif isinstance(existing, list) and isinstance(value, str):
                if value not in existing:
                    merged[key] = existing + [value]
            # Existing string, new list – append each new item after a period
            elif isinstance(existing, str) and isinstance(value, list):
                text = existing.rstrip('.')
                for v in value:
                    if v and v not in text:
                        text = f"{text}. {v}"
                merged[key] = text
            # Both strings – append new string after a period
            elif isinstance(existing, str) and isinstance(value, str):
                if existing == value:
                    merged[key] = existing
                else:
                    merged[key] = f"{existing.rstrip('.')}. {value}"

    # 5: Merge publication information by appending new values
    publication_information = state.get("publication_extracted_info", {}) or {}
    for key, value in publication_information.items():
        if key in ("current_version", "key_contributors"):
            continue
        existing = merged.get(key)
        if existing is None:
            merged[key] = value
        else:
            # Combine list and list
            if isinstance(existing, list) and isinstance(value, list):
                merged[key] = list(dict.fromkeys(existing + value))
            # Existing list, new string – keep list semantics
            elif isinstance(existing, list) and isinstance(value, str):
                if value not in existing:
                    merged[key] = existing + [value]
            # Existing string, new list – append each new item after a period
            elif isinstance(existing, str) and isinstance(value, list):
                text = existing.rstrip('.')
                for v in value:
                    if v and v not in text:
                        text = f"{text}. {v}"
                merged[key] = text
            # Both strings – append new string after a period
            elif isinstance(existing, str) and isinstance(value, str):
                if existing == value:
                    merged[key] = existing
                else:
                    merged[key] = f"{existing.rstrip('.')}. {value}"

    return {"raw_extracted_info": merged, "error_messages": merged_errors}


def remove_redundancy(state: GraphState) -> Dict:
    """
    Use an LLM to remove redundant or mismatched entries based on ModelCard field descriptions.
    """
    logging.info("--- Node: remove_redundancy ---")
    raw = state.get("raw_extracted_info", {}) or {}
    errors = state.get("error_messages", []) or []

    # Build field descriptions for prompting
    field_lines = "\n".join(
        f"- {name}: {field.description}"
        for name, field in ModelCard.model_fields.items()
    )

    # Prepare JSON payload
    raw_json = json.dumps(raw)

    prompt = ChatPromptTemplate.from_template(
        """You are given raw extracted metadata for a model card and the official field descriptions:
{fields}

Raw metadata (JSON):
{raw}

Please return a JSON object containing only the cleaned metadata: 
- Remove any duplicate or redundant entries.
- Ensure each value matches the corresponding field description.
- Omit any keys with values that do not match the description."""
    )

    formatted = prompt.format_prompt(fields=field_lines, raw=raw_json)
    llm_client = state.get("llm_client")
    try:
        ai_message = llm_client.invoke(formatted.to_messages())
        result_text = ai_message.content
        # Strip markdown fences if present
        cleaned_text = re.sub(r"```(?:json)?\s*", "", result_text).replace("```", "").strip()
        cleaned = json.loads(cleaned_text)
    except Exception as e:
        logging.error(f"LLM redundancy removal failed: {e}")
        errors.append(f"remove_redundancy error: {e}")
        cleaned = raw

    return {"extracted_info": cleaned}


if __name__ == "__main__":

    api_key = os.getenv("IM3_AZURE_OPENAI_API_KEY", default=None)
    endpoint = os.getenv("IM3_AZURE_OPENAI_ENDPOINT", default=None)
    deployment = "gpt-4o"
    openai_api_version = "2024-02-01"

    llm = AzureChatOpenAI(
        model_name="gpt-4o", 
        temperature=0.1, 
        api_key=api_key,
        openai_api_version=openai_api_version,
        azure_deployment=deployment,
        azure_endpoint=endpoint,
    )

    # --- Build the Graph ---
    workflow = StateGraph(GraphState)

    # Add other nodes as before
    workflow.add_node("fetch_github_release", fetch_github_release)
    workflow.add_node("fetch_github_contributors", fetch_github_contributors)
    workflow.add_node("fetch_github_repository", fetch_github_repository)
    workflow.add_node("extract_github_info", extract_github_info)
    workflow.add_node("merge_info", merge_info)
    workflow.add_node("remove_redundancy", remove_redundancy)
    workflow.add_node("error_handler", handle_error)
    workflow.add_node("build_model_card", build_model_card)
    workflow.add_node("extract_website_info", extract_website_info)
    workflow.add_node("fetch_publications_pdfs", fetch_publications_pdfs)
    workflow.add_node("extract_publication_info", extract_publication_info)
    workflow.add_node("fetch_website", fetch_website)

    # Add entry points so they run as their own agents
    workflow.set_entry_point("fetch_github_release")
    workflow.set_entry_point("fetch_github_contributors")
    workflow.set_entry_point("fetch_github_repository")
    workflow.set_entry_point("fetch_website")
    workflow.set_entry_point("fetch_publications_pdfs")

    # Connect agents
    workflow.add_edge("fetch_website", "extract_website_info")
    workflow.add_edge("extract_website_info", "merge_info")
    workflow.add_edge("fetch_publications_pdfs", "extract_publication_info")
    workflow.add_edge("extract_publication_info", "merge_info")
    workflow.add_edge("fetch_github_release", "merge_info")
    workflow.add_edge("fetch_github_contributors", "merge_info")
    workflow.add_edge("fetch_github_repository", "extract_github_info")
    workflow.add_edge("extract_github_info", "merge_info")

    # Remove direct edges from merge_info to build_model_card and error_handler, instead go through dedupe_info
    workflow.add_edge("merge_info", "remove_redundancy")
    workflow.add_edge("remove_redundancy", "build_model_card")
    workflow.add_edge("remove_redundancy", "error_handler")
    workflow.add_edge("build_model_card", END)
    workflow.add_edge("error_handler", END)

    # Compile the graph
    app = workflow.compile()

    # --- Run the Graph ---
    inputs = {
        "github_url": "https://github.com/ClimateGlobalChange/tempestextremes",
        "github_branch": "master",
        "extracted_info": {},
        "raw_extracted_info": {},
        "error_messages": [],
        "validation_issues": {},
        "model_card": None, # Ensure model_card starts as None
        "release_info": {},
        "github_release_errors": [],
        "contributors_info": {},
        "github_contributor_errors": [],
        "github_extracted_info": {},
        "github_repository_errors": [],
        "handled_errors": [],
        "llm_client": llm,
        "website_url": "https://climate.ucdavis.edu/tempestextremes.php",
        "website_content": None,
        "website_errors": [],
        "website_extracted_info": {},
        "publication_directory": "./data/publications",
        "publication_content": None,
        "publication_extracted_info": {},
        "publication_errors": [],
    }

    print("Starting graph execution...")

    final_state = app.invoke(inputs)

    print("\n--- Graph Execution Finished ---")

    # Check final state for success
    final_card_data = final_state.get("model_card")
    final_issues = final_state.get("validation_issues")
    final_errors = final_state.get("error_messages")
    final_errors = final_state.get("handled_errors", final_state.get("error_messages"))

    # Define success more strictly: model_card exists AND no validation issues AND no critical errors?
    # For now, rely on the routing logic: if it reached END without errors/issues routing it away.
    # A simple check is if final_card_data exists and final_issues is empty.
    if final_card_data and not final_issues:
        print("Successfully generated Model Card:")
        try:
            # Create the final Pydantic object from the dictionary state
            final_card = ModelCard(**final_card_data)

            print(final_card.model_dump_json(indent=2))

        except Exception as e:
            print(f"Error creating/printing final ModelCard object: {e}")
            print("Raw dictionary data:", final_card_data)
    else:
        print("Failed to generate valid Model Card.")
        print("Final State Details:")
        if final_errors:
            print("Errors:", final_errors)
        if final_issues:
            print("Validation Issues:", final_issues)
        
        print("Partial Card Data:", final_card_data) # Uncomment to see potentially invalid data
